### ISSUE TITLE
ERR unknown command 'FT._LIST'

### ISSUE THREAD

**Issue by Skhan-Origami** [redis-developer/redis-om-dotnet-skeleton-app#11]
I get the following on IndexCreationService;

Unhandled exception. StackExchange.Redis.RedisServerException: ERR unknown command 'FT._LIST'
   at Redis.OM.RedisConnection.ExecuteAsync(String command, String[] args)
   at Redis.OM.Skeleton.HostedServices.IndexCreationService.StartAsync(CancellationToken cancellationToken) in C:\Work\Projects\Redis-OM\redis-om-dotnet-skeleton-app\HostedServices\IndexCreationService.cs:line 19
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Microsoft.AspNetCore.Builder.WebApplication.Run(String url)
   at Program.<Main>$(String[] args) in C:\Work\Projects\Redis-OM\redis-om-dotnet-skeleton-app\Program.cs:line 28

With .net 6 SDK.

I am running docker locally with redis-stack.

**Comment by slorello89** [comment]
Hi @Skhan-Origami - I'm not familiar with any redis-stack version that does not have the command `FT._LIST`, my guess would be is that you are not in fact running with the `redis-stack` image, but rather with just the `redis` image.

**Comment by Skhan-Origami** [comment]
hi @slorello89, thanks for the quick reply. I just installed docker and my docker command is docker run -d -p 6379:6379 -p 8001:8001 redis/redis-stack:latest. What else should I try?

**Comment by slorello89** [comment]
what do you get when you run `redis-cli FT._LIST`?

**Comment by Skhan-Origami** [comment]
I get:  (empty array) 
![image](https://github.com/redis-developer/redis-om-dotnet-skeleton-app/assets/121190014/6b5930bc-d717-4f6c-9eb2-054675eaad22)

**Comment by Skhan-Origami** [comment]
This is embarrassing. My windows image had 'Redis for Windows' installed. I uninstalled it and it is all working. Sorry.

**Comment by slorello89** [comment]
well, there you have it, no worries. closing this issue.
